### ISSUE TITLE
Infografía  Jaczibeth 

### ISSUE THREAD

**Issue by Jaczibeth** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Jaczibeth#1]
[Infografia de los conceptos y funciones de una librerías o componentes y su aplicación en las Apps..pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Jaczibeth/files/14565474/Infografia.de.los.conceptos.y.funciones.de.una.librerias.o.componentes.y.su.aplicacion.en.las.Apps.pdf)

**Comment by EdgarExa** [comment]
20% de 20 bien hecho

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
